<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageProjectUrl>https://github.com/jdauie/Jacere.Progress</PackageProjectUrl>
    <Version>0.1.0</Version>
    <Title>Console Progress</Title>
    <Company />
    <Authors>jdauie</Authors>
    <PackageTags>console;terminal;powershell;progress</PackageTags>
    <RepositoryUrl>https://github.com/jdauie/Jacere.Progress</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\..\icon.png" Pack="true" PackagePath="\" Link="Docs\icon.png" />
		<None Include="..\..\LICENSE" Pack="true" PackagePath="\" Link="Docs\LICENSE" />
		<None Include="..\..\README.md" Pack="true" PackagePath="\" Link="Docs\README.md" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="ByteSize" Version="2.1.2" />
    <PackageReference Include="MinVer" PrivateAssets="All" Version="2.3.0" />
  </ItemGroup>

</Project>
